[functions]
  directory = "apps/api/functions"
  node_bundler = "esbuild"

[build]
  command = "npm run build:web"
  publish = "apps/web-react/dist"

[dev]
  functions = "apps/api/functions"
  publish = "."

# Route a simple mini UI at /web to apps/web
[[redirects]]
  from = "/web"
  to = "/apps/web/index.html"
  status = 200

# React UI at /react (production points to built assets)
[[redirects]]
  from = "/react"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api-docs"
  to = "/apps/web-react/public/api-docs.html"
  status = 200


# SPA fallback for React UI nested routes only (does not affect /api/*)
[[redirects]]
  from = "/react/*"
  to = "/index.html"
  status = 200

# Alternate route to bypass any CDN path caching for troubleshooting
[[redirects]]
  from = "/react2"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/react2/*"
  to = "/index.html"
  status = 200


[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Netlify-CDN-Cache-Control = "public, max-age=0, must-revalidate"

