[functions]
  directory = "apps/api/functions"
  node_bundler = "esbuild"

[build]
  command = "npm run build:web"
  publish = "apps/web-react/dist"

[dev]
  functions = "apps/api/functions"
  publish = "."

# Landing page at /
[[redirects]]
  from = "/"
  to = "/landing.html"
  status = 200
  force = true

# Route a simple mini UI at /web to apps/web
[[redirects]]
  from = "/web"
  to = "/apps/web/index.html"
  status = 200

[[headers]]
  for = "/landing.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Netlify-CDN-Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Netlify-CDN-Cache-Control = "public, max-age=0, must-revalidate"

# React UI at /react (production points to built assets)
[[redirects]]
  from = "/react"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api-docs"
  to = "/api-docs.html"
  status = 200


# SPA fallback for React UI nested routes only (does not affect /api/*)
[[redirects]]
  from = "/react/*"
  to = "/index.html"
  status = 200

# Alternate route to bypass any CDN path caching for troubleshooting
[[redirects]]
  from = "/react2"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/react2/*"
  to = "/index.html"
  status = 200

# API routes → Netlify Functions (explicit mappings used by UI)
[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200

[[redirects]]
  from = "/api/auth/signup"
  to = "/.netlify/functions/auth-signup"
  status = 200


[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Netlify-CDN-Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/react"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co https://*.sentry.io; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self'; frame-ancestors 'none'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), interest-cohort=(), payment=()"

[[headers]]
  for = "/api-docs.html"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://unpkg.com 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://unpkg.com; img-src 'self' data:; connect-src 'self' https://raw.githubusercontent.com; frame-ancestors 'none'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"

