[functions]
  directory = "apps/api/functions"
  node_bundler = "esbuild"

[dev]
  functions = "apps/api/functions"
  publish = "."

# Route a simple mini UI at /web to apps/web
[[redirects]]
  from = "/web"
  to = "/apps/web/index.html"
  status = 200

# React UI at /react (production points to built assets)
[[redirects]]
  from = "/react"
  to = "/apps/web-react/dist/index.html"
  status = 200


