name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npx tsc -p tsconfig.json --noEmit

      - name: Run tests
        run: npm test

      - name: Validate OpenAPI
        run: npx --yes @redocly/cli@latest lint docs/api/openapi.yaml

      - name: Supabase Advisors (optional)
        run: node scripts/advisors.mjs
        env:
          SUPABASE_PAT: ${{ secrets.SUPABASE_PAT }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          STRICT_ADVISORS: ${{ secrets.STRICT_ADVISORS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || secrets.GITHUB_TOKEN }}

      - name: EXPLAIN baselines (optional)
        if: ${{ secrets.SUPABASE_URL != '' && secrets.SUPABASE_SERVICE_ROLE_KEY != '' }}
        run: node scripts/explain.mjs
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          EXPLAIN_MAX_ROWS: ${{ secrets.EXPLAIN_MAX_ROWS }}
          EXPLAIN_STRICT: ${{ secrets.EXPLAIN_STRICT }}

      - name: Preview smoke against deployed URL (optional)
        if: ${{ secrets.DEPLOYED_BASE_URL != '' }}
        run: node scripts/smoke.mjs
        env:
          BASE_URL: ${{ secrets.DEPLOYED_BASE_URL }}

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npx tsc -p tsconfig.json --noEmit

      - name: Run tests
        run: npm test --silent

      - name: Build web
        run: npm run build:web --silent

  openapi-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate OpenAPI
        uses: char0n/swagger-editor-validate@v1
        with:
          files: |
            docs/api/openapi.yaml

  supabase-advisors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Run advisors (non-blocking)
        env:
          SUPABASE_PAT: ${{ secrets.SUPABASE_PAT }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          STRICT_ADVISORS: 'false'
        run: node scripts/advisors.mjs || true
      - name: Open/update Advisors issue
        env:
          SUPABASE_PAT: ${{ secrets.SUPABASE_PAT }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: node scripts/advisors-report.mjs || true

  explain-baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Run EXPLAIN baselines (non-blocking)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node scripts/explain.mjs || true

  preview-smoke:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Smoke against preview URL
        env:
          BASE_URL: ${{ github.event.pull_request.head.repo.fork == true && '' || format('https://{0}--{1}.netlify.app', github.head_ref || github.ref_name, 'tiny-bombolone-8f8acf') }}
        run: |
          if [ -z "$BASE_URL" ]; then echo "Skipping (fork PR or unable to resolve preview URL)"; exit 0; fi
          echo "BASE_URL=$BASE_URL"
          node -e "(async()=>{const f=await fetch('$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/raw/$GITHUB_SHA/scripts/smoke.mjs'); const t=await f.text(); await import('data:text/javascript,'+encodeURIComponent(t));})()"


