name: Smoke Tests

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: Base URL to test (e.g., https://tiny-bombolone-8f8acf.netlify.app)
        required: true
      token:
        description: Optional Authorization header value (e.g., Bearer <JWT>)
        required: false
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Run smoke tests
        env:
          BASE_URL: ${{ github.event.inputs.base_url }}
          TOKEN: ${{ github.event.inputs.token }}
        run: npm run smoke


